org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1024m
org.gradle.parallel=true
org.gradle.caching=false

project.build.group=net.runelite
project.build.version=1.12.31-SNAPSHOT
runelite.injected-client.version=1.12.31-SNAPSHOT

glslang.path=

microbot.version=2.6.6
microbot.commit.sha=nogit
microbot.repo.url=http://138.201.81.246:8081/repository/microbot-snapshot/
microbot.repo.username=
microbot.repo.password=
